--角色

--角色权限
delete  from PUB_ROLE_RESOURCE WHERE ROLE_ID='SUPERADMIN';
delete  from PUB_ROLE_RESOURCE WHERE ROLE_ID='SYSADMIN';
delete  from PUB_ROLE_RESOURCE WHERE ROLE_ID='GPUBLIC';

delete  from PUB_TROLE_OPTS WHERE ROLE_ID='SUPERADMIN';
delete  from PUB_TROLE_OPTS WHERE ROLE_ID='SYSADMIN';
delete  from PUB_TROLE_OPTS WHERE ROLE_ID='GPUBLIC';

--为预定义系统角色赋予功能资源权限
INSERT INTO PUB_ROLE_RESOURCE SELECT 'SUPERADMIN',RESOURCE_ID FROM PUB_RESOURCES ;
INSERT INTO PUB_ROLE_RESOURCE SELECT 'SYSADMIN',RESOURCE_ID FROM PUB_RESOURCES WHERE FUNCTION_ID IN(SELECT FUNCTION_ID FROM PUB_FUNCTIONS WHERE IS_SYS='1');
INSERT INTO PUB_ROLE_RESOURCE SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'BASE%' ;
INSERT INTO PUB_ROLE_RESOURCE SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'PUBTOOL%' ;


--为缺省模板中的预定义系统角色赋予功能资源权限 
INSERT INTO PUB_TROLE_OPTS SELECT 'SUPERADMIN',RESOURCE_ID FROM PUB_RESOURCES ;
INSERT INTO PUB_TROLE_OPTS SELECT 'SYSADMIN',RESOURCE_ID FROM PUB_RESOURCES WHERE FUNCTION_ID IN(SELECT FUNCTION_ID FROM PUB_FUNCTIONS WHERE IS_SYS='1');
INSERT INTO PUB_TROLE_OPTS SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'BASE%' ;
INSERT INTO PUB_TROLE_OPTS SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'PUBTOOL%' ;


COMMIT;
