--工作流workform table id
INSERT INTO PUB_IDTABLE VALUES('WF_WORKFORM_ID',3000,'WF_WORKFORM_ID',1,NULL,'1',10,'0','0','1',NULL);
INSERT INTO PUB_IDTABLE VALUES('WF_PRINT_TEMPLET_ID',0,'WF_PRINT_TEMPLET_ID',1,NULL,'1',10,'0','0','1',NULL);
--工作流公用生成最大号
INSERT INTO PUB_IDTABLE VALUES('WF_MAX_ID',0,'WF_MAX_ID',1,NULL,'1',15,'0','0','1',NULL);
--工作流报表
INSERT INTO PUB_IDTABLE VALUES ('WF_REPORT_ID',0,'WF_REPORT_ID',1,NULL,'0',10,'0',NULL,'1',NULL);
--任务代理表主键最大号
INSERT INTO PUB_IDTABLE VALUES ('WF_TASKACCREDIT_ID',0,'WF_TASKACCREDIT_ID',1,NULL,'0',10,'0',NULL,'1',NULL);
--通用流程表 主键最大号
INSERT INTO PUB_IDTABLE VALUES ('WF_UNIPROCESS_ID',0,'WF_UNIPROCESS_ID',1,NULL,'0',20,'0',NULL,'1',NULL);
