
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('2013', '工作流程', '工作流程', '0', NULL, NULL, 'icon:Pictureviewer.jpg',NULL);

INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('20131', '任务管理', '任务列表', '0', NULL, NULL, NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201311', '新建任务', '新建任务', '0', 'processlist.cmd?method=processlist', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201312', '待办任务', '待办任务', '0', 'taskinfodaiban.cmd?method=getProcessTypeList', 'main',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201313', '在办任务', '在办任务', '0', 'taskinfozaiban.cmd?method=getProcessTypeList', 'main', NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201314', '已办任务', '已办任务', '0', 'taskinfoyiban.cmd?method=getProcessTypeList', 'main', NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201315', '结束任务', '结束任务', '0', 'taskinfofinish.cmd?method=getProcessTypeList', 'main', NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201316', '角色任务', '角色任务', '0', 'taskinforole.cmd?method=getProcessTypeList', 'main', NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201317', '监控任务', '监控任务', '0', 'taskinfomonitor.cmd?method=getProcessTypeList', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201318', '出差代理', '出差代理', '0', 'wftaskaccreditquery.cmd?clearsearch=true', 'main',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201319', '通用流程', '通用流程', '0', 'wfuniprocessquery_page_init.cmd', 'main',NULL, NULL);

--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('20132', '查询管理', '查询管理', '0', NULL, NULL, NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201320', '流程查询', '流程查询', '0', 'taskquery.cmd', 'main',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201321', '表单查询', '表单查询', '0', 'workformforquery.cmd', 'main',NULL, NULL);

INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201331', '工作流统计分析', NULL, '0', NULL, NULL, NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201332', '持续时间', NULL, '0', NULL, NULL, NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201333', '业务流量', NULL, '0', NULL, NULL, NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201334', '季度平均持续时间', NULL, '0', 'wflasttime.cmd?method=processLastTimeByQuarter', 'main', NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201335', '月平均持续时间', NULL, '0', 'wflasttime.cmd?method=processLastTimeByYear', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201336', '日平均持续时间', NULL, '0', 'wflasttime.cmd?method=processLastTimeByMonth', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201337', '季度业务流量', NULL, '0', 'wfportfolio.cmd?method=processPortfolioByQuarter', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201338', '月业务流量', NULL, '0', 'wfportfolio.cmd?method=processPortfolioByYear', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201339', '日业务流量', NULL, '0', 'wfportfolio.cmd?method=processPortfolioByMonth', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('201340', '人员业务量分析', NULL, '0', 'wfpersonanlyze.cmd?method=PersonSelectPro', 'main',NULL, NULL);

--工作流报表
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201341', '流程报表管理', '流程报表管理', '0', 'wfreport.cmd?method=gettreeeditroot', '_tree',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('201343', '报表管理', '报表管理', '0', 'wfrptquery.cmd?method=querygettreeeditroot', '_tree',NULL, NULL);

--流程管理
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('1013', '流程管理', '流程管理', '0', NULL, NULL, 'icon:kfmk.gif', NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('10131', '流程类型', '流程类型', '0', 'processtypequery.cmd?clear=true', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('10132', '表单管理', '表单管理', '0', 'workformmanagerquery.cmd?clear=true', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('10133', '工作流程', '工作流程', '0', 'processquery.cmd?clear=true', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('10134', '缓存管理', '缓存管理', '0', 'wfadminoperate.cmd?method=cacheAdmin', 'main',NULL, NULL);
INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
VALUES ('10135', '流程监控', '流程监控', '0', 'processmgradminquery.cmd?clear=true', 'main',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('10136', '工作流升级', '工作流升级', '0', 'upgrade.cmd?method=upgrade', 'main',NULL, NULL);
--INSERT INTO PUB_MENU_SYSITEM (MENU_ID, TEXT, TITLE, TYPE, VALUE, TARGET,OPTIONS,FUNCTION_ID)
--VALUES ('10137', '签名图片', '签名图片', '0', 'signpic.cmd?method=query', 'main',NULL, NULL);



INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES('2013','2013', '01', '工作流程', 'BSP000000000000000000000000001', 10, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('20131','20131','01','任务管理','2013', 0, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201311','201311','01','新建任务', '20131', 1, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201312', '201312','01','待办任务','20131', 2, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201313','201313','01', '在办任务', '20131', 3, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201314','201314','01', '已办任务', '20131', 4, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201315','201315','01', '结束任务', '20131', 5, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201316','201316','01', '角色任务', '20131', 6, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201317','201317','01', '监控任务', '20131', 7, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201318','201318','01', '出差代理', '20131', 8, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201319','201319','01', '通用流程', '20131', 9, '0');

--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('20132','20132','01', '查询管理', '2013', 1, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201320','201320','01', '流程查询', '20132', 0, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201321','201321','01', '表单查询', '20132', 1, '0');

--工作流报表
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201341','201341','01', '流程报表管理', '1013', 5, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('201343','201343','01', '报表管理', '2013', 2, '0');

INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('1013','1013','01', '流程管理', 'BSP000000000000000000000000001', 11, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('10131','10131','01', '流程类型', '1013', 0, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('10132','10132','01', '表单管理', '1013', 1, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('10133','10133','01', '工作流程', '1013', 2, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('10134','10134','01', '缓存管理', '1013', 3, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('10135','10135','01', '流程监控', '1013', 4, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('10136','10136','01', '工作流升级', '1013', 5, '0');
--INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
--VALUES ('10137','10137','01', '签名图片', '1013',6, '0');

INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201331','201331','01', '工作流统计分析', 'BSP000000000000000000000000001', 12, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201332','201332','01', '持续时间', '201331', 0, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201333','201333','01', '业务流量', '201331', 1, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201334','201334','01', '季度平均持续时间', '201332', 0, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201335','201335','01', '月平均持续时间', '201332', 1, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201336','201336','01', '日平均持续时间', '201332', 2, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201337','201337','01', '季度业务流量', '201333', 0,'0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201338','201338','01', '月业务流量', '201333', 1, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201339','201339','01', '日业务流量', '201333', 2, '0');
INSERT INTO PUB_MENU_SYS(MENU_SYS_ID,MENU_ID,TYPE_ID,MENU_ALIAS,PARENT_ID,SEQ,IS_LEAF) 
VALUES ('201340','201340','01', '人员业务量分析', '201331', 2, '0');

