--1.初始化   20060720 毛玲燕---------------------
--初始化数据---------------------
CREATE TABLE PUB_MAIL_ACCOUNT
(
            ACCOUNT_ID VARCHAR (30) NOT NULL ,
            USER_ID VARCHAR (30) NOT NULL ,
            POP3_SERVER VARCHAR (80) ,
            SMTP_SERVER VARCHAR (80) NOT NULL ,
            MAIL_USER_ID VARCHAR (30) NOT NULL ,
            MAIL_PASSWORD VARCHAR (128) NOT NULL ,
            MAIL_ADDRESS VARCHAR (80) NOT NULL,
            MAIL_USER_NAME VARCHAR (80) NOT NULL ,            
            IS_AUTO_RECEIVE CHAR (1) default '0' ,
            INTERVAL INTEGER ,
            STATUS CHAR (1) default '1' ,
            IN_USE CHAR (1) default '1' ,
            IMAP_SERVER VARCHAR (80) ,
            SERVER_TYPE CHAR(1)
) ; 

CREATE TABLE PUB_MAIL_RESOURCE
(
            RESOURCE_ID VARCHAR (30) NOT NULL ,
            ACCOUNT_ID VARCHAR (30) NOT NULL ,
            SENDER_NAME VARCHAR (80) NOT NULL ,
            SEND_FROM VARCHAR (80) NOT NULL ,
            SEND_CC VARCHAR(4000) ,
            SEND_TO VARCHAR(4000) ,
            SUBJECT VARCHAR (200) NOT NULL ,
            CONTENT LONG RAW,
            MAIL_SIZE INTEGER ,
            MAIL_TYPE CHAR (1) ,
            PRIORITY CHAR (1) ,
            STATUS CHAR (1) ,
            IS_RETURN_RECEIPT CHAR (1) ,
            SEND_TIME CHAR (17) NOT NULL,
            IS_SCHEDULE CHAR (1) default '0',
            SCHEDULE_TIME CHAR(17) default ' ',
            DESCRIPTION VARCHAR(400) default ' '
) ; 
CREATE TABLE PUB_MAIL_ATTACHMENT_REF
(
            ID VARCHAR (30) NOT NULL ,
            RESOURCE_ID VARCHAR (30) NOT NULL ,
            FILE_ID VARCHAR (30) NOT NULL 
) ; 

CREATE TABLE PUB_MAIL_ADDRESS_CATEGORY
(
            CATEGORY_ID VARCHAR (30) NOT NULL ,
            USER_ID VARCHAR (30) NOT NULL ,
            CATEGORY_NAME VARCHAR (80) NOT NULL 
) ; 

CREATE TABLE PUB_MAIL_GROUP_CARD_REF
(
            ID VARCHAR (30) NOT NULL ,
            GROUP_ID VARCHAR (30) NOT NULL ,
            CARD_ID VARCHAR (30) NOT NULL 
) ; 

CREATE TABLE PUB_MAIL_ADDRESS
(
            ADDRESS_ID VARCHAR (30) NOT NULL ,
            ADDRESS_NAME VARCHAR (80) NOT NULL ,
            ADDRESS_EMAIL VARCHAR (80) ,
            ADDRESS_TYPE CHAR (1) NOT NULL ,
            CATEGORY_ID VARCHAR (30) NOT NULL 
) ; 

CREATE TABLE PUB_MAIL_BLACKLIST
(
            BLACKLIST_ID VARCHAR (30) NOT NULL ,
            USER_ID VARCHAR (30) NOT NULL ,
            BLACKLIST_NAME VARCHAR (80) NOT NULL ,
            BLACKLIST_EMAIL VARCHAR (80) 
) ; 

CREATE TABLE PUB_COMMON_PARMS
(
            PARMS_CODE VARCHAR (30) NOT NULL ,
            PARMS_NAME VARCHAR (30) NOT NULL ,
            PARMS_VALUE VARCHAR (250) NOT NULL ,
            NOTE VARCHAR (250)
) ;


ALTER TABLE PUB_MAIL_ACCOUNT
    ADD CONSTRAINT MailAccount_PK 
    PRIMARY KEY (ACCOUNT_ID);
 ALTER TABLE PUB_MAIL_RESOURCE
    ADD CONSTRAINT MailResource_PK 
    PRIMARY KEY (RESOURCE_ID);
 ALTER TABLE PUB_MAIL_ATTACHMENT_REF
    ADD CONSTRAINT MailAttachmentR_PK 
    PRIMARY KEY (ID);
 ALTER TABLE PUB_MAIL_ADDRESS_CATEGORY
    ADD CONSTRAINT MailAddressCate_PK 
    PRIMARY KEY (CATEGORY_ID);
 ALTER TABLE PUB_MAIL_GROUP_CARD_REF
    ADD CONSTRAINT MailGroupCardRe_PK 
    PRIMARY KEY (ID);
 ALTER TABLE PUB_MAIL_ADDRESS
    ADD CONSTRAINT MailAddress_PK 
    PRIMARY KEY (ADDRESS_ID);
 ALTER TABLE PUB_MAIL_BLACKLIST
    ADD CONSTRAINT MailBlacklist_PK 
    PRIMARY KEY (BLACKLIST_ID);
