CREATE TABLE WF_REPORT
(
            REPORTID VARCHAR (10) NOT NULL ,
            FORMID VARCHAR (10) NOT NULL ,
            FLOWID VARCHAR (20) ,
            REPORTNAME VARCHAR (50) NOT NULL ,
            RANGE CHAR (1) default '1' NOT NULL
) ;

CREATE TABLE WF_REPORTDEFINE
(
            REPORTID VARCHAR (10) NOT NULL ,
            R_DEMENSION VARCHAR (1023) NOT NULL ,
            C_DEMENSION VARCHAR (1023) NOT NULL ,
            DATA_TARTGET VARCHAR (1023) NOT NULL ,
            R_STAT VARCHAR (254) NOT NULL ,
            C_STAT VARCHAR (254) NOT NULL ,
            DATA_SUM VARCHAR (254) NOT NULL
) ;

ALTER TABLE WF_REPORT
    ADD CONSTRAINT WfReport_PK
    PRIMARY KEY (REPORTID);
ALTER TABLE WF_REPORTDEFINE
    ADD CONSTRAINT WfReportDefine_PK
    PRIMARY KEY (REPORTID);