--在ADJUNCTANDTEXT中添加字段EXTENDFIELD
CREATE TABLE ADJUNCTANDTEXT (
	ID varchar (255)  NOT NULL ,
	DATAID varchar (255)  NOT NULL ,
	SUBTIME timestamp ,
	USERID varchar (255) ,
	USERNAME varchar (255) ,
	CONTENT LONG RAW ,
	TITLE varchar (255) ,
	EXTENDNAME varchar (60)  default 'doc',
	FILENAME varchar (255) ,
	TYPENAME varchar (10),
	EXTENDFIELD varchar(255)
);
CREATE TABLE EDITDATA (
	ID varchar (255)  NOT NULL ,
	DATAID varchar (255)  NOT NULL ,
	FIELDNAME varchar (60) ,
	CONTENT LONG RAW
);
--在SPECIALEDITDATA表中增加两个字段:ACTDEFID ,ACINAME
CREATE TABLE SPECIALEDITDATA (
	ID varchar (255)  NOT NULL ,
	DATAID varchar (255)  NOT NULL ,
	ACTDEFID varchar (255) ,
	ACTNAME varchar (255) ,
	FIELDNAME varchar (60) ,
	SUBTIME timestamp ,
	USERID varchar (255) ,
	USERNAME varchar (255) ,
	CONTENT LONG RAW,
	SENDED varchar (10) 
);
CREATE TABLE SUGGESTDATA (
	ID varchar (255)  NOT NULL ,
	DATAID varchar (255)  NOT NULL ,
	SUBTIME timestamp ,
	USERID varchar (255) ,
	USERNAME varchar (255) ,
	CONTENT LONG RAW
);
CREATE TABLE SELECTDATA (
	ID varchar (255)  NOT NULL ,
	DATAID varchar (255)  NOT NULL ,
	FIELDNAME varchar (60) ,
	DISPLAYURL varchar (255) ,
	DISPLAYSTR varchar (255) ,
	KEYVALUE varchar (255),
	FORMID varchar(255)  
);
CREATE TABLE FORMPRINTTEMPLET
(
    ID VARCHAR (40) NOT NULL ,
    FORMID VARCHAR (30) NOT NULL ,
    PROCESSID VARCHAR (30) NOT NULL ,
    TEMPLETNAME VARCHAR (100) NOT NULL ,
    EXTENDNAME VARCHAR (10) NOT NULL ,
    NOTE VARCHAR (200) ,
    CONTENT LONG RAW 
);
CREATE TABLE FORMTEMPLATE
(
	FORMID VARCHAR(100) NOT NULL,
	FILENAME VARCHAR(100) NOT NULL,
	TEMPLATE LONG RAW 
);
CREATE TABLE WORKFORM
(
	FORMID VARCHAR(100) NOT NULL,
	FORMXML LONG RAW 
);

ALTER TABLE ADJUNCTANDTEXT
    ADD CONSTRAINT ADJUNCTANDTEXT_PK 
    PRIMARY KEY (ID,DATAID);
ALTER TABLE EDITDATA
    ADD CONSTRAINT EDITDATA_PK 
    PRIMARY KEY (ID,DATAID);    
ALTER TABLE SPECIALEDITDATA
    ADD CONSTRAINT SPECIALEDITDATA_PK 
    PRIMARY KEY (ID,DATAID);      
ALTER TABLE SUGGESTDATA
    ADD CONSTRAINT SUGGESTDATA_PK 
    PRIMARY KEY (ID,DATAID);    
ALTER TABLE SELECTDATA
    ADD CONSTRAINT SELECTDATA_PK 
    PRIMARY KEY (ID,DATAID);
ALTER TABLE FORMPRINTTEMPLET
    ADD CONSTRAINT FORMPRINTTEMPLET_PK 
    PRIMARY KEY (ID);
ALTER TABLE FORMTEMPLATE
    ADD CONSTRAINT FORMTEMPLATE_PK 
    PRIMARY KEY (FORMID,FILENAME); 
ALTER TABLE WORKFORM
    ADD CONSTRAINT WORKFORM_PK 
    PRIMARY KEY (FORMID);     
CREATE VIEW VADJUNCTANDTEXT AS SELECT ID,DATAID,SUBTIME,USERID,USERNAME,TITLE,EXTENDNAME,FILENAME,TYPENAME,EXTENDFIELD FROM ADJUNCTANDTEXT;   

