--File组件测试
CREATE TABLE MAINBLOB
(
    MAIN_ID VARCHAR (30) NOT NULL,
    MAIN_OPERATORCODE VARCHAR (30) NOT NULL,
    MAIN_OPERATEDATE VARCHAR (8) NOT NULL
);

CREATE TABLE BLOBITEM
(
    MAIN_ID VARCHAR (30) NOT NULL,
    FILE_ID VARCHAR (30) NOT NULL,
    FILE_NAME VARCHAR (100),
    FILE_TYPE VARCHAR (30),
    FILE_CONTENT LONG RAW
);
ALTER TABLE MAINBLOB ADD CONSTRAINT MAINBLOB_PK PRIMARY KEY (MAIN_ID);
ALTER TABLE BLOBITEM ADD CONSTRAINT BLOBITEM_PK PRIMARY KEY (MAIN_ID,FILE_ID);
ALTER TABLE BLOBITEM ADD CONSTRAINT BLOBITEM_FK1 FOREIGN KEY (MAIN_ID) REFERENCES MAINBLOB (MAIN_ID);

--员工信息
CREATE TABLE LS_EMPLOYEE
(
            EMPLOYEE_CODE VARCHAR (30) NOT NULL ,
            EMPLOYEE_SEX CHAR (1) NOT NULL ,
            EMPLOYEE_NAME VARCHAR (30) NOT NULL ,
            EMPLOYEE_AGE INTEGER NOT NULL ,
            EMPLOYEE_MARRY CHAR (1) NOT NULL ,
            EMPLOYEE_BIRTH CHAR (8) NOT NULL ,
            EMPLOYEE_ENTER_DATE CHAR (8) NOT NULL ,
            EMPLOYEE_COMPANY VARCHAR (30) NOT NULL ,
            EMPLOYEE_DEGREE VARCHAR (2) NOT NULL ,
            EMPLOYEE_FAX VARCHAR (15) NOT NULL ,
            EMPLOYEE_COUNTRY VARCHAR (15) NOT NULL ,
            EMPLOYEE_PROVINCE VARCHAR (15) NOT NULL ,
            EMPLOYEE_CITY VARCHAR (15) NOT NULL ,
            EMPLOYEE_PHONE CHAR (11) NOT NULL ,
            EMPLOYEE_DEPT VARCHAR (15) NOT NULL ,
            EMPLOYEE_POST CHAR (6) NOT NULL ,
            EMPLOYEE_PREFERENCE VARCHAR (8) NOT NULL ,
            EMPLOYEE_IMAGECONTENT LONG RAW ,
            EMPLOYEE_NOTE VARCHAR (100) NOT NULL 
);
ALTER TABLE LS_EMPLOYEE ADD CONSTRAINT LS_EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_CODE);

--树形结构
CREATE TABLE ORGAN_STRU
(
            ORGAN_ID VARCHAR (30) NOT NULL ,
            ORGAN_ALIAS VARCHAR (80) NOT NULL ,
            ORGAN_TYPE VARCHAR (10) NOT NULL ,
            PARENT_ID VARCHAR (30) ,
            PRINCIPAL_ID VARCHAR (30) ,
            STRU_PATH VARCHAR (250) NOT NULL ,
            ORGAN_ORDER INTEGER default 1 NOT NULL ,
            BEGIN_DATE CHAR (8) NOT NULL ,
            END_DATE CHAR (8) default '99991231' NOT NULL ,
            IS_LEAF CHAR (1) default '0' NOT NULL 
);
ALTER TABLE ORGAN_STRU ADD CONSTRAINT ORGAN_STRU_PK PRIMARY KEY (ORGAN_ID);
--查询网格
CREATE TABLE FLEXGRID
(
            FLEX_ID VARCHAR (30) NOT NULL ,
            FLEX_TEXT VARCHAR (30) NOT NULL ,
            FLEX_CURRENCY VARCHAR (30) NOT NULL ,
            FLEX_DATE VARCHAR (30) NOT NULL ,
            FLEX_NUMERIC VARCHAR (30) NOT NULL ,
            FLEX_ENUM CHAR (1) NOT NULL ,
            FLEX_LISTENUM VARCHAR (10) NOT NULL , 
            EMPLOYEE_COUNTRY VARCHAR  (30) NOT NULL ,
            EMPLOYEE_PROVINCE VARCHAR  (30) NOT NULL ,
            EMPLOYEE_CITY VARCHAR  (30) NOT NULL ,
	    FLEX_SQL VARCHAR (30) NOT NULL 
);
ALTER TABLE FLEXGRID ADD CONSTRAINT FLEXGRID_PK PRIMARY KEY (FLEX_ID);
--编辑网格
CREATE TABLE MAIN_GRID
(
            MAIN_GRID_ID VARCHAR (30) NOT NULL ,
            OPERATOR_CODE VARCHAR (30) NOT NULL ,
            OPERATE_NAME VARCHAR (30) NOT NULL ,
            OPERATE_COOPERATE VARCHAR (30) NOT NULL ,
            OPERATE_DEPT VARCHAR (30) NOT NULL ,
            OPERATE_DATE CHAR (8) NOT NULL ,
            OPERATE_EFFDATE CHAR (8) NOT NULL ,
            OPERATOR_STATUS CHAR (1) default '1' NOT NULL ,
            OPERATOR_DEPOT CHAR (1) default '1' NOT NULL 
);

CREATE TABLE GRID_ITEM
(
            MAIN_GRID_ID VARCHAR (30) NOT NULL ,
            ITEM_DETAILID VARCHAR (30) NOT NULL ,
            ITEM_PRODUCTID VARCHAR (30) NOT NULL ,
            ITEM_UNITPRICE DECIMAL (5,2) ,
            ITEM_DISCOUNT CHAR (1) NOT NULL ,
            ITEM_QUANTITY DECIMAL (5,2) ,
            ITEM_AMOUNT DECIMAL (5,2) ,
            ITEM_DATE VARCHAR (8) NOT NULL ,
            ITEM_DATETIME VARCHAR (17) NOT NULL ,
            ITEM_LEVEL CHAR (1) default '0' NOT NULL ,
            ITEM_NOTE VARCHAR (50) NOT NULL 
);
--商品信息
CREATE TABLE PRODUCT
(
            ITEM_PRODUCTID VARCHAR (30) NOT NULL ,
            ITEM_PRODUCTNAME VARCHAR (30) NOT NULL ,
            ITEM_UNITPRICE DECIMAL (5,2) NOT NULL ,
            ITEM_QUANTITY DECIMAL (5,2) NOT NULL ,
            ITEM_AMOUNT DECIMAL (5,2) NOT NULL ,
            ITEM_LEVEL CHAR (1) default '0' NOT NULL 
);

ALTER TABLE MAIN_GRID ADD CONSTRAINT MainGrid_PK PRIMARY KEY (MAIN_GRID_ID);
ALTER TABLE GRID_ITEM ADD CONSTRAINT GridItem_PK PRIMARY KEY (MAIN_GRID_ID,ITEM_DETAILID);
ALTER TABLE PRODUCT ADD CONSTRAINT Product_PK PRIMARY KEY (ITEM_PRODUCTID);

ALTER TABLE GRID_ITEM ADD CONSTRAINT GridItem_FK1 FOREIGN KEY (MAIN_GRID_ID) REFERENCES MAIN_GRID (MAIN_GRID_ID);
----tab组件
--计划
CREATE TABLE LS_PLAN
(
            PLAN_ID VARCHAR (30) NOT NULL ,
            PLAN_TYPE CHAR (1) default '1' NOT NULL ,
            ORGAN_ID VARCHAR (30) NOT NULL ,
            PLAN_NAME VARCHAR (30) NOT NULL ,
            PLAN_PERIOD VARCHAR (6) NOT NULL ,
            CREATOR_ID VARCHAR (30) NOT NULL ,
            CREATE_DATE CHAR (10) NOT NULL ,
            PLAN_STATE CHAR (1) default '0' NOT NULL 
);

--任务项
CREATE TABLE LS_TASK
(
            TASK_ID VARCHAR (30) NOT NULL ,
            PLAN_ID VARCHAR (30) NOT NULL ,
            TASK VARCHAR (100) NOT NULL ,
            FINISH_DATE CHAR (10) NOT NULL ,
            PERFECT_SCORE INTEGER NOT NULL ,
            CHECKMAN_ID VARCHAR (30) NOT NULL ,
            ACHIVED_SCORE INTEGER 
);

--生成主键
ALTER TABLE LS_PLAN ADD CONSTRAINT LsPlan_PK PRIMARY KEY (PLAN_ID);    
ALTER TABLE LS_TASK ADD CONSTRAINT LsTask_PK PRIMARY KEY (TASK_ID);

----组合框
CREATE TABLE COMBOBOX_TEST
(
    COMBOBOX_ID VARCHAR (30) NOT NULL,
    COMBOBOX_NAME VARCHAR (30) NOT NULL,
    COMBOBOX_SEX CHAR (1) default '0',
    COMBOBOX_NATION CHAR (1) default '0',
    COMBOBOX_ADDRESS VARCHAR (30) default '0'
);

CREATE TABLE COMBO_COLLECTION
(
    COMBO_ID VARCHAR (30) NOT NULL,
    COMBO_NAME VARCHAR (30) NOT NULL,
    COMBO_HELP VARCHAR (30) NOT NULL
);

ALTER TABLE COMBOBOX_TEST ADD CONSTRAINT C_T_PK PRIMARY KEY (COMBOBOX_ID);
ALTER TABLE COMBO_COLLECTION ADD CONSTRAINT C_C_PK PRIMARY KEY (COMBO_ID);

--商品
CREATE TABLE GOODS
(
	GOODS_ID VARCHAR (32) NOT NULL,
	GOODS_NAME VARCHAR (32) NOT NULL,
	GOODS_PRICE VARCHAR (32) NOT NULL
);
ALTER TABLE GOODS ADD CONSTRAINT C_GOODS_PK PRIMARY KEY (GOODS_ID);
--厂家
CREATE TABLE FACTORY
(
	FACTORY_ID VARCHAR (32) NOT NULL,
	FACTORY_NAME VARCHAR (32) NOT NULL,
	FACTORY_ADDRESS VARCHAR (32) NOT NULL,	
	GOODS_ID VARCHAR (32) NOT NULL
);

ALTER TABLE FACTORY ADD CONSTRAINT C_FACTORY_PK PRIMARY KEY (FACTORY_ID);
ALTER TABLE FACTORY ADD CONSTRAINT FACTORY_FK1 FOREIGN KEY (GOODS_ID) REFERENCES GOODS(GOODS_ID);

--商品
CREATE TABLE FOOD
(
	FOOD_ID VARCHAR (32) NOT NULL,
	FOOD_NAME VARCHAR (32) NOT NULL,
	FOOD_ORIGIN VARCHAR (32) NOT NULL,	
	FOOD_NUM VARCHAR (32) NOT NULL,
	FOOD_PRICE VARCHAR (32) NOT NULL,
	XB_ID VARCHAR (32) NOT NULL
);
ALTER TABLE FOOD ADD CONSTRAINT C_FOOD_PK PRIMARY KEY (FOOD_ID);