--消息
CREATE TABLE MP_MESSAGE
(
            MSG_ID VARCHAR (30) NOT NULL ,
            MSG_TYPE_CODE VARCHAR (30) NOT NULL ,
            OBJECTID VARCHAR (30) ,
            SUBJECT VARCHAR (100) NOT NULL ,
            CONTENT VARCHAR (1024) NOT NULL ,
            SCHEDULE CHAR (14) ,
            USEFUL_TIME CHAR (14) ,
            CREATE_TIME CHAR (17) ,
            CREATER VARCHAR (30) ,
            RECEIVE_ADDRESS VARCHAR (1024) ,
            RECEIVE_MANNER_CODE VARCHAR (30) ,
            ATTACHMENT BLOB ,
            STATUS VARCHAR (10) 
);


--消息错误诊断
CREATE TABLE MP_MESSAGE_HOSPITAL
(
            ERROR_MSG_ID VARCHAR (30) NOT NULL ,
            MSG_ID VARCHAR (30) NOT NULL ,
            SEND_TIME CHAR (17) ,
            RECEIVE_ADDRESS VARCHAR (30) ,
            RECEIVE_MANNER_CODE VARCHAR (30) ,
            STATUS VARCHAR (10) ,
            DESCRIPTION VARCHAR (200) 
);


--历史消息
CREATE TABLE MP_MESSAGE_HISTORY
(
            MSG_ID VARCHAR (30) NOT NULL ,
            MSG_TYPE_CODE VARCHAR (30) NOT NULL ,
            OBJECTID VARCHAR (30) ,
            SUBJECT VARCHAR (100) NOT NULL ,
            CONTENT VARCHAR (1024) NOT NULL ,
            SCHEDULE CHAR (14) ,
            USEFUL_TIME CHAR (14) ,
            CREATE_TIME CHAR (17) ,
            SEND_TIME CHAR (17) ,
            CREATER VARCHAR (30) ,
            RECEIVE_ADDRESS VARCHAR (1024) ,
            RECEIVE_MANNER_CODE VARCHAR (30) ,
            ATTACHMENT BLOB ,
            STATUS VARCHAR (10) 
);


--用户消息
CREATE TABLE MP_USER_MESSAGE
(
            USER_MESSAGE_ID VARCHAR (30) NOT NULL ,
            MSG_TYPE_CODE VARCHAR (30) NOT NULL ,
            SUBSCRIBERID VARCHAR (30) NOT NULL ,
            SUBSCR_TYPE_CODE VARCHAR (30) NOT NULL ,
            SUBJECT VARCHAR (100) NOT NULL ,
            CONTENT VARCHAR (1024) NOT NULL ,
            CREATER VARCHAR (30) ,
            CREATE_TIME CHAR (17) ,
            ARRIVE_TIME CHAR (17) ,
            ATTACHMENT BLOB ,
            STATUS VARCHAR (10) 
);


--消息订阅列表
CREATE TABLE MP_SUBSCR_LIST
(
            SUBSCR_ID VARCHAR (30) NOT NULL ,
            MSG_TYPE_CODE VARCHAR (30) NOT NULL ,
            SUBSCRIBERID VARCHAR (30) NOT NULL ,
            SUBSCR_TYPE_CODE VARCHAR (30) NOT NULL ,
            RECEIVE_MANNER_CODE VARCHAR (30) NOT NULL ,
            RECEIVE_ADDRESS VARCHAR (30) ,
            FILTER VARCHAR (30),
            EXTENDINFO VARCHAR (30) 
);


--消息类型
CREATE TABLE MP_MESSAGE_TYPE
(
            MSG_TYPE_CODE VARCHAR (30) NOT NULL ,
            MSG_TYPE_NAME VARCHAR (30) NOT NULL ,
            IS_COMMON_MSG CHAR (1) default '0' NOT NULL ,
            OBJECT_TABLE_NAME VARCHAR (30) ,
            SUBSCR_LIMIT VARCHAR (100)  NOT NULL ,
            MANNER_LIMIT VARCHAR (100)  NOT NULL 
);



--订阅者类型
CREATE TABLE MP_SUBSCRIBER_TYPE
(
            SUBSCR_TYPE_CODE VARCHAR (30) NOT NULL ,
            SUBSCR_TYPE_NAME VARCHAR (30) NOT NULL 
);


--订阅/接收方式
CREATE TABLE MP_INCEPT_MANNER
(
            RECEIVE_MANNER_CODE VARCHAR (30) NOT NULL ,
            RECEIVE_MANNER_NAME VARCHAR (30) NOT NULL 
);


--订阅地址
CREATE TABLE MP_RECEIVE_ADDRESS
(
            RECEIVE_ADDRESS_ID VARCHAR (30) NOT NULL ,
            SUBSCR_TYPE_CODE VARCHAR (30) NOT NULL ,
            RECEIVE_MANNER_CODE VARCHAR (30) NOT NULL ,
            OBJECT_TABLE_NAME VARCHAR (30) NOT NULL ,
            SUBSCRIBERID_FIELD VARCHAR (30) NOT NULL ,
            SUBSCRIBERID_FIELD_TYPE VARCHAR (10) default 'String' NOT NULL ,
            ADDRESS_FIELD VARCHAR (30) NOT NULL 
);

ALTER TABLE MP_MESSAGE
    ADD CONSTRAINT MpMessage_PK 
    PRIMARY KEY (MSG_ID);
 ALTER TABLE MP_MESSAGE_HOSPITAL
    ADD CONSTRAINT MpMessageHospit_PK 
    PRIMARY KEY (ERROR_MSG_ID);
 ALTER TABLE MP_MESSAGE_HISTORY
    ADD CONSTRAINT MpMessageHistor_PK 
    PRIMARY KEY (MSG_ID);
 ALTER TABLE MP_USER_MESSAGE
    ADD CONSTRAINT MpUserMessage_PK 
    PRIMARY KEY (USER_MESSAGE_ID);
 ALTER TABLE MP_SUBSCR_LIST
    ADD CONSTRAINT MpSubscrList_PK 
    PRIMARY KEY (SUBSCR_ID);
 ALTER TABLE MP_MESSAGE_TYPE
    ADD CONSTRAINT MpMessageType_PK 
    PRIMARY KEY (MSG_TYPE_CODE);
 ALTER TABLE MP_SUBSCRIBER_TYPE
    ADD CONSTRAINT MpSubscriberTyp_PK 
    PRIMARY KEY (SUBSCR_TYPE_CODE);
 ALTER TABLE MP_INCEPT_MANNER
    ADD CONSTRAINT MpInceptManner_PK 
    PRIMARY KEY (RECEIVE_MANNER_CODE);
 ALTER TABLE MP_RECEIVE_ADDRESS
    ADD CONSTRAINT MpReceiveAddres_PK 
    PRIMARY KEY (RECEIVE_ADDRESS_ID);

