--PUB_MODULES 模块
----工作流
INSERT INTO  pub_modules(MODULE_ID, MODULE_NAME, PARENT_MODULE_ID, IS_LEAF, SEQ ) VALUES ( 'WORKFLOW', '工作流', 'WORKFLOW', '1', null );

--PUB_FUNCTIONS 功能
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW01', 'WORKFLOW01', '工作流类型管理', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW02', 'WORKFLOW02', '表单管理', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW03', 'WORKFLOW03', '流程管理', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW04', 'WORKFLOW04', '任务列表定制', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW05', 'WORKFLOW05', '表单打印模板', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW06', 'WORKFLOW06', '任务管理', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW07', 'WORKFLOW07', '附件操作', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW08', 'WORKFLOW08', '流程操作', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW09', 'WORKFLOW09', '流程监控', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW10', 'WORKFLOW10', '表单操作', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW11', 'WORKFLOW11', '流程查询', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW12', 'WORKFLOW12', '缓存管理', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW13', 'WORKFLOW13', '流程监控', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW14', 'WORKFLOW14', '字号维护', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW15', 'WORKFLOW15', '组织树选择', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WORKFLOW16', 'WORKFLOW16', '工作流统计分析', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WFREPORT15', 'WFREPORT15', '工作流报表', 'WORKFLOW', '0', null, null );
INSERT INTO  pub_functions(FUNCTION_ID, FUNCTION_CODE, FUNCTION_NAME, MODULE_ID, IS_SYS, DATA_RES_TYPE, SEQ ) VALUES ( 'WFREPORT16', 'WFREPORT16', '工作流报表查询', 'WORKFLOW', '0', null, null );

--PUB_FUNCTIONS 资源
--工作流类型管理
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0101', '查询', '查询工作流类型', 'processtypequery.cmd;processtype.cmd?method=detail;processtype.cmd?method=isExist', 0, 'WORKFLOW01', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0102', '增加', '增加工作流类型', 'processtype.cmd?method=forinsert;processtype.cmd?method=insert', 0, 'WORKFLOW01', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0103', '修改', '修改工作流类型', 'processtype.cmd?method=forupdate;processtype.cmd?method=update', 0, 'WORKFLOW01', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0104', '删除', '删除工作流类型', 'processtype.cmd?method=delete', 0, 'WORKFLOW01', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0105', '流程类型帮助', '流程类型帮助', 'processtypehelpquery.cmd', 0, 'WORKFLOW01', '1', '0', '00', null );
--增加历史环节类型帮助
INSERT INTO  PUB_RESOURCES(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES('WORKFLOW0106','历史环节类型帮助','历史环节类型帮助','historyhelpurlquery.cmd',0,'WORKFLOW01','1','0', '00', null );


--表单管理
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0201', '查询', '查询表单', 'workformmanagerquery.cmd?clear=true;formmanager.cmd?method=detail;formmanager.cmd?method=render;formdataquery.cmd?method=query;formdataquery.cmd;formmanager.cmd?method=getReserveKeysXml;formmanager.cmd?method=getEditFieldsXml;formmanager.cmd?method=getSelectFieldsXml;formmanager.cmd?method=getSpecialEditsXml;formmanager.cmd?method=getVerifysXml;formmanager.cmd?method=getDynamicDefaultsXml;formmanager.cmd?method=getFixedFieldsXml', 0, 'WORKFLOW02', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0202', '增加', '增加表单', 'formmanager.cmd?method=forinsert;processtypehelpquery.cmd;formmanager.cmd?method=insert;struhelp.cmd?method=getSelectRoot;struhelp.cmd?method=getHelpTreeNode;formmanager.cmd?method=getReserveKeysXml;formmanager.cmd?method=getEditFieldsXml;formmanager.cmd?method=getSelectFieldsXml;formmanager.cmd?method=getSpecialEditsXml;formmanager.cmd?method=getVerifysXml;formmanager.cmd?method=getDynamicDefaultsXml;formmanager.cmd?method=getFixedFieldsXml', 0, 'WORKFLOW02', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0203', '修改', '修改表单', 'formmanager.cmd?method=forupdate;formmanager.cmd?method=update;struhelp.cmd?method=getSelectRoot;struhelp.cmd?method=getHelpTreeNode', 0, 'WORKFLOW02', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0204', '删除', '删除表单', 'formmanager.cmd?method=delete', 0, 'WORKFLOW02', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0205', '明细', '表单明细', 'formmanager.cmd?method=detail;formmanager.cmd?method=render;formdataquery.cmd?method=query;formdataquery.cmd;formmanager.cmd?method=getReserveKeysXml;formmanager.cmd?method=getEditFieldsXml;formmanager.cmd?method=getSelectFieldsXml;formmanager.cmd?method=getSpecialEditsXml;formmanager.cmd?method=getVerifysXml;formmanager.cmd?method=getDynamicDefaultsXml;formmanager.cmd?method=getFixedFieldsXml', 0, 'WORKFLOW02', '1', '0', '00', null );
--建表操作
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0206', '建表', '新建数据库表', 'formmanager.cmd?method=createTables', 0, 'WORKFLOW02', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0207', '图片', '图片展现', 'workformgraph.cmd?method=exec; workformgraph.cmd?method= getfiles; workformgraph.cmd?method= updateFile', 0, 'WORKFLOW02', '1', '0', '00', null );
--流程管理
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0301', '查询', '查询流程', 'processquery.cmd;process.cmd?method=detail;urlconfig.cmd?method=urlGetSystemConfig;urlconfig.cmd?method=urlGetMenuConfig;urlconfig.cmd?method=getActorFields;urlconfig.cmd?method=getWorkform;urlconfig.cmd?method=urlGetProcess;urlconfig.cmd?method=urlGetSystemOrgan;struhelp.cmd?method=getSelectRoot;struhelp.cmd?method=getHelpTreeNode;roleradio.cmd?method=choiceroot;role.cmd?method=choicenode;workformmanagerhelpquery.cmd;processtemplatequery.cmd;role.cmd?method=getSysRoleRoot;role.cmd?method=getSysRoleNode', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0302', '增加', '增加流程', 'jspFormsHelpQuery.cmd;process.cmd?method=forinsertpro;processtypehelpquery.cmd;process.cmd?method=forinsert;process.cmd?method=insert;process.cmd?method=insertLoad;urlconfig.cmd?method=urlGetSystemConfig;urlconfig.cmd?method=urlGetMenuConfig;urlconfig.cmd?method=getActorFields;urlconfig.cmd?method=getWorkform;urlconfig.cmd?method=getDefinedForm;urlconfig.cmd?method=getDcworkform;urlconfig.cmd?method=getJspForm;urlconfig.cmd?method=urlGetProcess;urlconfig.cmd?method=urlGetSystemOrgan;struhelp.cmd?method=getSelectRoot;struhelp.cmd?method=getHelpTreeNode;roleradio.cmd?method=choiceroot;role.cmd?method=choicenode;workformmanagerhelpquery.cmd;processtemplatequery.cmd', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0303', '修改', '修改流程', 'process.cmd?method=forupdatepro;process.cmd?method=forupdate;process.cmd?method=update;process.cmd?method=loadProcess;process.cmd?method=load;process.cmd?method=syndata;process.cmd?method=updateNewVer;urlconfig.cmd?method=urlGetSystemConfig;urlconfig.cmd?method=urlGetMenuConfig;urlconfig.cmd?method=getActorFields;urlconfig.cmd?method=getWorkform;urlconfig.cmd?method=urlGetProcess;urlconfig.cmd?method=urlGetSystemOrgan;struhelp.cmd?method=getSelectRoot;struhelp.cmd?method=getHelpTreeNode;roleradio.cmd?method=choiceroot;role.cmd?method=choicenode;workformmanagerhelpquery.cmd;processtemplatequery.cmd', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0304', '删除', '删除流程', 'process.cmd?method=delete', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0305', '明细', '流程明细', 'process.cmd?method=detail;urlconfig.cmd?method=urlGetSystemConfig;urlconfig.cmd?method=urlGetMenuConfig;urlconfig.cmd?method=getActorFields;urlconfig.cmd?method=getWorkform;urlconfig.cmd?method=urlGetProcess;urlconfig.cmd?method=urlGetSystemOrgan', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0306', '流程导入', '流程导入', 'processExchange.cmd?method=forimport;processExchange.cmd?method=doimport;', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0307', '流程导出', '流程导出', 'processExchange.cmd?method=forexport;processExchange.cmd?method=export;', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0308', '工作流升级', '工作流升级', 'upgrade.cmd?method=upgrade;upgrade.cmd?method=upgradeTable;upgrade.cmd?method=upgradeData;', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0309', '流程定义帮助', '流程定义帮助', 'processhelpquery.cmd', 0, 'WORKFLOW03', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0400', '签名图片', '签名图片', 'signpic.cmd?method=query;signpic.cmd?method=delete;signpic.cmd?method=detail;signpic.cmd?method=forInsert;signpic.cmd?method=insert', 0, 'WORKFLOW03', '1', '0', '00', null );
--增加流程类型通用帮助
INSERT INTO  PUB_RESOURCES(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES('WORKFLOW0406','增加流程类型','通用帮助的cmd','wfYwHelpInitquery.cmd',0,'WORKFLOW03','1','0', '00', null );
--增加同步监控人
INSERT INTO  PUB_RESOURCES(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES('WORKFLOW0405','同步监控人','同步监控人','process.cmd?method=synReposible',0,'WORKFLOW03','1','0', '00', null );
--jsp表单定义请求url查询
INSERT INTO  PUB_RESOURCES(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES('WORKFLOW0407','jsp表单定义请求url查询','jsp表单定义请求url查询cmd','jspFormRequestsHelpQuery.cmd',0,'WORKFLOW03','1','0', '00', null );


--任务列表定制
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0401', '查询', '查询任务列表定制', 'tasklistquery.cmd;tasklist.cmd?method=detail;', 0, 'WORKFLOW04', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0402', '增加', '增加任务列表定制', 'tasklist.cmd?method=getReservekeys;tasklist.cmd?method=insert', 0, 'WORKFLOW04', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0403', '修改', '修改任务列表定制', 'tasklist.cmd?method=forupdate;tasklist.cmd?method=update', 0, 'WORKFLOW04', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0404', '删除', '删除任务列表定制', 'tasklist.cmd?method=delete', 0, 'WORKFLOW04', '1', '0', '00', null );

--表单打印模板
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0501', '查询', '查询打印模板', 'formprinttempletquery.cmd;formprinttemplet.cmd?method=detail', 0, 'WORKFLOW05', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0502', '增加', '增加打印模板', 'formprinttemplet.cmd?method=forinsert;formprinttemplet.cmd?method=insert', 0, 'WORKFLOW05', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0503', '修改', '修改打印模板', 'formprinttemplet.cmd?method=forupdate;formprinttemplet.cmd?method=update', 0, 'WORKFLOW05', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0504', '删除', '删除打印模板', 'formprinttemplet.cmd?method=delete', 0, 'WORKFLOW05', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0505', '选择模板', '选择模板', 'formprinttemplethelp.cmd;formprinttemplet.cmd?method=detailHidden', 0, 'WORKFLOW05', '1', '0', '00', null );

--任务列表
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0601', '新建', '新建任务', 'processlist.cmd?method=processlist;taskinfo.cmd?method=forcreate;taskinfo.cmd?method=createdocument;taskinfo.cmd?method=printForm', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0602', '待办', '待办任务', 'taskinfodaiban.cmd?method=getProcessTypeList;taskinfodaiban.cmd?method=getProcessList;taskinfoquery.cmd;taskinfo.cmd?method=fordeal;taskinfo.cmd?method=mpfordeal', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0603', '在办', '在办任务', 'taskinfozaiban.cmd?method=getProcessTypeList;taskinfozaiban.cmd?method=getProcessList;taskinfoquery.cmd;taskinfo.cmd?method=fordeal;taskinfo.cmd?method=mpfordeal', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0604', '已办', '已办任务', 'taskinfoyiban.cmd?method=getProcessTypeList;taskinfoyiban.cmd?method=getProcessList;oldtaskinfoquery.cmd;taskinfo.cmd?method=forold;taskinfo.cmd?method=mpforold', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0605', '结束', '结束任务', 'taskinfofinish.cmd?method=getProcessTypeList;taskinfofinish.cmd?method=getProcessList;finishtaskinfoquery.cmd;taskinfo.cmd?method=forend', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0606', '角色', '角色任务', 'taskinforole.cmd?method=getProcessTypeList;taskinforole.cmd?method=getProcessList;roletaskinfoquery.cmd;taskinfo.cmd?method=forrole;taskinfo.cmd?method=delegate', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0607', '监控', '监控任务', 'taskinfomonitor.cmd?method=getProcessTypeList;taskinfomonitor.cmd?method=getProcessList;restaskinfoquery.cmd;edocmonitorinfoquery.cmd;taskinfo.cmd?method=forres;edocmonitorinfo.cmd?method=detail', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0608', '所有', '所有任务', 'taskinfoforemp.cmd?method=getTaskInfoForEmp;taskinfoforemp.cmd?method=getProcessList_daiban;taskinfoforemp.cmd?method=getProcessList_zaiban;taskinfoforemp.cmd?method=getProcessList_yiban;taskinfoforemp.cmd?method=getProcessList_finish', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0609', '出差代理', '出差代理', 'wftaskaccreditquery.cmd;wftaskaccredit.cmd?method=detail;wftaskaccredit.cmd?method=forinsert;wftaskaccredit.cmd?method=insert;wftaskaccredit.cmd?method=insertContinue;wftaskaccredit.cmd?method=forupdate;wftaskaccredit.cmd?method=update;wftaskaccredit.cmd?method=delete;', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0610', '通用流程', '通用流程', 'wfuniprocessquery_page_init.cmd;wfuniprocessquery_page_init.cmd?helpQuery=true;wfuniprocess.cmd?method=forDeal;wfuniprocess.cmd?method=save;wfuniprocess.cmd?method=forward;wfuniprocess.cmd?method=delete', 0, 'WORKFLOW06', '1', '0', '00', null );
INSERT INTO  PUB_RESOURCES(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES('WORKFLOW0611','jsp表单操作','jsp表单操作','jspformtaskdeal.cmd?method=forcreate; jspformtaskdeal.cmd?method= fordeal; jspformtaskdeal.cmd?method= forold ; jspformtaskdeal.cmd?method= forend;jspformtaskdeal.cmd?method=forres;jspformtaskdeal.cmd?method= forrole; jspformtaskdeal.cmd?method= delegate',0,'WORKFLOW06','1','0', '00', null );


--附件操作
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0701', '查询', '查询附件', 'adjunctquery.cmd;adjunct.cmd?method=detail', 0, 'WORKFLOW07', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0702', '增加', '增加附件', 'adjunct.cmd?method=forinsert;adjunct.cmd?method=insert', 0, 'WORKFLOW07', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0703', '删除', '删除附件', 'adjunct.cmd?method=delete', 0, 'WORKFLOW07', '1', '0', '00', null );
--2006.04.20增加选择附件的URL
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0704', '附件选择', '附件选择', 'adjuncthelpquery.cmd', 0, 'WORKFLOW07', '1', '0', '00', null );

--流程操作
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0801', '保存数据', '保存数据', 'taskinfo.cmd?method=saveformdata', 0, 'WORKFLOW08', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0802', '创建发送', '创建发送', 'taskinfo.cmd?method=createAndSend', 0, 'WORKFLOW08', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0803', '发送', '发送', 'taskinfo.cmd?method=send', 0, 'WORKFLOW08', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0804', '选择发送', '选择发送', 'taskinfo.cmd?method=getnextactivities;partynextactivityquery.cmd;taskinfo.cmd?method=send', 0, 'WORKFLOW08', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0805', '退回', '退回', 'taskinfo.cmd?method=gethistoryactivities;taskinfo.cmd?method=jump;taskinfo.cmd?method=retract;edocmonitorinfoquery.cmd&infoType=7', 0, 'WORKFLOW08', '1', '0', '00', null );
--2006.04.20新增流程定义选择URL
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW0806', '流程定义', '流程定义单选', 'processhelpurlquery.cmd', 0, 'WORKFLOW08', '1', '0', '00', null );

--流程监控

--表单操作
--属于公文扩展的资源也把它加进来 开始
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1003', '添加常用意见', '添加常用意见', 'commonremark.cmd?method=specialeditAdd', 0, 'WORKFLOW10', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1004', '删除常用意见', '删除常用意见', 'commonremark.cmd?method=specialeditDelete', 0, 'WORKFLOW10', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1005', '常用审批意见', '常用审批意见', 'commonremark.cmd?method=specialeditremarkdialog', 0, 'WORKFLOW10', '1', '0', '00', null );
--属于公文扩展的资源也把它加进来 结束
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1006', '签名域', '签名域', 'taskinfo.cmd?method=signdialog', 0, 'WORKFLOW10', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1007', '选择域', '选择域', 'wf_struhelp.cmd?method=getEmpRoot;wf_struhelp.cmd?method=getCheckEmpRoot;wfdochelpcheckbox.cmd;wfdochelpradio.cmd;wfmeetinghelp.cmd;wf_struhelp.cmd?method=getSelectRoot;wf_struhelp.cmd?method=getHelpTreeNode', 0, 'WORKFLOW10', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1008', '交流', '交流', 'actionexchangequery.cmd;actionexchange.cmd?method=forinsert;actionexchange.cmd?method=insert;dochelpcheckbox.cmd', 0, 'WORKFLOW10', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1009', '正文', '正文', 'doccontent.cmd?method=detail', 0, 'WORKFLOW10', '1', '0', '00', null );

--流程查询
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1101', '流程查询', '流程查询', 'taskquery.cmd;taskinfosearch.cmd?method=search;taskinfosearch.cmd?method=forsearch;hrempforhelpradio.cmd;wf_struhelp.cmd?method=getEmpRoot;wf_struhelp.cmd?method=getChoiceNode;wfdochelpcheckbox.cmd;wfdochelpradio.cmd;wfmeetinghelp.cmd', 0, 'WORKFLOW11', '1', '0', '00', null );
--表单查询
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1102', '表单查询', '表单查询', 'workformforquery.cmd;formmanager.cmd?method=render;formdataquery.cmd;', 0, 'WORKFLOW11', '1', '0', '00', null );
--后台管理
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1201', '缓存管理', '缓存管理', 'wfadminoperate.cmd?method=cacheAdmin;wfadminoperate.cmd?method=forSetCacheSize;wfadminoperate.cmd?method=setCacheSize;wfadminoperate.cmd?method=clearCache', 0, 'WORKFLOW12', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1301', '流程监控', '流程监控', 'processmgradminquery.cmd?clear=true;processendadminquery.cmd;wfadminquery.cmd?method=getProcessList;wfadminquery.cmd?method=getAssignmentEndList;wfadminquery.cmd?method=getActivityEndList;wfadminquery.cmd?method=getAssignmentList;wfadminquery.cmd?method=getActivityList;processmgr.cmd?method=forupload;processmgr.cmd?method=uploadProcess;processmgr.cmd?method=startProcessMgr;processmgr.cmd?method=stopProcessMgr;processmgr.cmd?method=deleteProcessMgr;activityadmin.cmd?method=suspendActivity;activityadmin.cmd?method=resumeActivity;activityadmin.cmd?method=abortActivity;activityadmin.cmd?method=terminateActivity;activityadmin.cmd?method=showhistoryActivity;assignmentadmin.cmd?method=cancelAssignment;assignmentadmin.cmd?method=reAssignment;assignmentadmin.cmd?method=closeAssignment;processadmin.cmd?method=suspendProcess;processadmin.cmd?method=resumeProcess;processadmin.cmd?method=abortProcess;processadmin.cmd?method=terminateProcess;processadmin.cmd?method=terminateProcessAndDeleteProcessEnd;processadmin.cmd?method=showhistoryProcess;processadmin.cmd?method=checklimitProcess;processadmin.cmd?method=historyCompare;processalladmin.cmd?method=startActivity;processalladmin.cmd?method=suspendProcess;processalladmin.cmd?method=resumeProcess;processalladmin.cmd?method=abortProcess;processalladmin.cmd?method=terminateProcess;processalladmin.cmd?method=terminateProcessAndDeleteProcessEnd;processalladmin.cmd?method=showhistoryProcess;processalladmin.cmd?method=checklimitProcess;processalladmin.cmd?method=historyCompare;processalladminquery.cmd;taskinfo.cmd?method=displaystatus;processendadmin.cmd?method=deleteProcessEnd', 0, 'WORKFLOW13', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1302', '启动环节', '流程监控', 'activityadmin.cmd?method=startActivity', 0, 'WORKFLOW13', '1', '0', '00', null );

--2005.11.29修正
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1501', '工作流组织树选择', '工作流组织树选择', 'wf_struhelp.cmd;struhelp.cmd;wforgantypequery.cmd', 0, 'WORKFLOW15', '1', '0', '00', null );

--工作流统计分析
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1601', '人员业务量分析', '人员或组织的业务量分析', 'wfpersonanlyze.cmd?method=PersonAnalyzeByDay;wfpersonanlyze.cmd?method=PersonSelectPro;wfpersonanlyze.cmd?method=PersonAnalyze;wfpersonanlyze.cmd?method=PersonAnalyzeByQuarter;wfpersonanlyze.cmd?method=PersonAnalyzeByMonth;', 0, 'WORKFLOW16', '0', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1602', '业务流量', '流程或流程类型的业务量', 'wfportfolio.cmd?method=processPortfolioByQuarter;wfportfolio.cmd?method=processPortfolioByMonth;wfportfolio.cmd?method=processPortfolioByYear;processhelpquery.cmd', 0, 'WORKFLOW16', '0', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WORKFLOW1603', '持续时间', '流程或环节的持续时间', 'wflasttime.cmd?method=activityLastTime;wflasttime.cmd?method=processLastTimeByQuarter;wflasttime.cmd?method=processLastTimeByMonth;wflasttime.cmd?method=processLastTimeByYear;', 0, 'WORKFLOW16', '0', '0', '00', null );

--工作流报表
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1501', '明细', '表单树', 'wfreport.cmd?method=gettreeeditroot', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1502', '明细', '表单树叶子', 'wfreport.cmd?method=gettreeeditbranch', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1503', '表单明细', '表单明细', 'wfreport.cmd?method=queryForm', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1504', '增加报表', '增加报表', 'wfreport.cmd?method=forinsert', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1505', '修改报表', '修改报表', 'wfreport.cmd?method=forupdate', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1506', '保存报表', '保存报表', 'wfreport.cmd?method=insert', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1507', '报表明细', '报表明细', 'wfreport.cmd?method=query', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1508', '报表明细', '报表明细修改', 'wfreport.cmd?method=update', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1509', '报表明细', '保存并继续', 'wfreport.cmd?method=insertContinue', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1510', '报表定义', '报表定义查询', 'wfreportdefine.cmd?method=detail', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1511', '删除报表', '删除报表', 'wfreport.cmd?method=delete', 0, 'WFREPORT15', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1512', '报表定义', '报表定义保存', 'wfreportdefine.cmd?method=insert', 0, 'WFREPORT15', '1', '0', '00', null );

INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1601', '明细', '查询表单树', 'wfrptquery.cmd?method=querygettreeeditroot', 0, 'WFREPORT16', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1602', '明细', '查询表单树叶子', 'wfrptquery.cmd?method=querygettreeeditbranch', 0, 'WFREPORT16', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1603', '报表查询', '报表查询', 'wfreportdefine.cmd?method=forquery', 0, 'WFREPORT16', '1', '0', '00', null );
INSERT INTO  pub_resources(RESOURCE_ID, RESOURCE_NAME, RESOURCE_ALIAS, URL_NAMES, SECURITY_LEVEL, FUNCTION_ID, IS_DEFAULT, IS_AUDIT, RES_TYPE_ID, SEQ ) VALUES ( 'WFREPORT1604', '报表查询', '报表查询', 'wfreportdefine.cmd?method=query', 0, 'WFREPORT16', '1', '0', '00', null );
