--先删除 出差代理表
drop table WF_TASKACCREDIT;
--出差代理
CREATE TABLE WF_TASKACCREDIT
(
                ID VARCHAR (36) NOT NULL ,
                OLDORGANID VARCHAR (30) ,
                AGENTORGANID VARCHAR (30) ,
                TYPE CHAR (1) NOT NULL ,
                DATAID VARCHAR (100) ,
                DATANAME VARCHAR (100) ,
                TIME VARCHAR (18) ,
                DESCRIPTION VARCHAR (100) ,
                ENDTIME VARCHAR (18) ,
                FLAG INT NOT NULL ,
                NOTE VARCHAR (30) ,
                NOTE2 VARCHAR (30) ,
                NOTE3 VARCHAR (30) 
);
ALTER TABLE WF_TASKACCREDIT
    ADD CONSTRAINT WfTaskaccredit_PK 
    PRIMARY KEY (ID);


CREATE  INDEX WF_TACTTYPE ON WF_TASKACCREDIT (TYPE);
CREATE  INDEX FLAG ON WF_TASKACCREDIT (FLAG);

---
--流程选择帮助
INSERT INTO PUB_COMHELP(HELP_ID, HELP_TITLE, HELP_SQL, ID_FIELD, NAME_FIELD, SHOW_FIELD, RETURN_FIELD, SHEARCH_FIELD, SHOW_NAME, HELP_TABLE, HELP_NOTE, DATASOURCE, NOTE, NOTE2, NOTE3 ) VALUES ( 'wf_processhelp', '流程选择', 'select WF_PROCESS_MGR.DEFINITION_ID , WF_PROCESS_MGR.PROCESS_NAME from WF_PROCESS_MGR WF_PROCESS_MGR,(select DEFINITION_ID,max(PROC_VERSION) PROC_VERSION from WF_PROCESS_MGR group by DEFINITION_ID) x where WF_PROCESS_MGR.PROC_VERSION=x.PROC_VERSION and WF_PROCESS_MGR.DEFINITION_ID=x.DEFINITION_ID', 'DEFINITION_ID', 'PROCESS_NAME', 'PROCESS_NAME', 'DEFINITION_ID,PROCESS_NAME', 'PROCESS_NAME', 'DEFINITION_ID#流程定义ID#,PROCESS_NAME#流程名称#200', 'WF_PROCESS_MGR', '显示所有已经载入的流程', '', '', '', '' ); 
--更新功能资源
update PUB_RESOURCES set  URL_NAMES='wftaskaccreditquery.cmd;wftaskaccredit.cmd' where RESOURCE_ID='WORKFLOW0609';

