DELETE  FROM PUB_ROLE_RESOURCE WHERE ROLE_ID='SUPERADMIN';
DELETE  FROM PUB_ROLE_RESOURCE WHERE ROLE_ID='SYSADMIN';
DELETE  FROM PUB_ROLE_RESOURCE WHERE ROLE_ID='GPUBLIC';

DELETE  FROM PUB_TROLE_OPTS WHERE ROLE_ID='SUPERADMIN';
DELETE  FROM PUB_TROLE_OPTS WHERE ROLE_ID='SYSADMIN';
DELETE  FROM PUB_TROLE_OPTS WHERE ROLE_ID='GPUBLIC';

--为预定义系统角色赋予功能资源权限
INSERT INTO PUB_ROLE_RESOURCE SELECT 'SUPERADMIN',RESOURCE_ID FROM PUB_RESOURCES ;
INSERT INTO PUB_ROLE_RESOURCE SELECT 'SYSADMIN',RESOURCE_ID FROM PUB_RESOURCES WHERE FUNCTION_ID IN(SELECT FUNCTION_ID FROM PUB_FUNCTIONS WHERE IS_SYS='1');
INSERT INTO PUB_ROLE_RESOURCE SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'BASE%' ;

--为缺省模板中的预定义系统角色赋予功能资源权限 
INSERT INTO PUB_TROLE_OPTS SELECT 'SUPERADMIN',RESOURCE_ID FROM PUB_RESOURCES ;
INSERT INTO PUB_TROLE_OPTS SELECT 'SYSADMIN',RESOURCE_ID FROM PUB_RESOURCES WHERE FUNCTION_ID IN(SELECT FUNCTION_ID FROM PUB_FUNCTIONS WHERE IS_SYS='1');
INSERT INTO PUB_TROLE_OPTS SELECT 'GPUBLIC',RESOURCE_ID FROM PUB_RESOURCES WHERE RESOURCE_ID LIKE 'BASE%' ;
    
COMMIT;