<%@ page contentType="text/html;charset=GBK" %>
<%
   		String countNumber=(String)request.getAttribute("countNumber");
		String firstDay = (String)request.getAttribute("firstDay");
		String nextWorkDay = (String)request.getAttribute("nextWorkDay");
		String nextNworkDay = (String)request.getAttribute("nextNworkDay");
		String preWorkDay = (String)request.getAttribute("preWorkDay");
		String preNworkDay = (String)request.getAttribute("preNworkDay");
		String hasWorkDay1 = (String)request.getAttribute("hasWorkDay1");
		String hasWorkDay2 = (String)request.getAttribute("hasWorkDay2");
out.println("获取在20050101, 20060101之间工作日的天数，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------countNumber:"+countNumber);
out.println("<br>");
out.println("获取在20050101, 20050120之间的第一个工作日，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------firstDay:"+firstDay);
out.println("<br>");
out.println("获取在20050101的下一个工作日，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------nextWorkDay:"+nextWorkDay);
out.println("<br>");
out.println("获取在20050101的下一个非工作日，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------nextNworkDay:"+nextNworkDay);
out.println("<br>");
out.println("获取在20050101的前一个工作日，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------preWorkDay:"+preWorkDay);
out.println("<br>");
out.println("获取在20050101的前一个非工作日，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------preNworkDay:"+preNworkDay);
out.println("<br>");
out.println("判断在2004年是否有工作日历，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------hasWorkDay1:"+hasWorkDay1);
out.println("<br>");
out.println("判断在2003年是否有工作日历，其中组织内码是1 :");
out.println("<br>");
out.println("--------------------------------hasWorkDay2:"+hasWorkDay2);
out.println("<br>");
%>