--Õ®”√—°‘Ò
CREATE TABLE PUB_COMHELP(
	HELP_ID VARCHAR (36) NOT NULL ,
	HELP_TITLE VARCHAR (80) NOT NULL ,
	HELP_SQL VARCHAR (2000) NOT NULL ,
	ID_FIELD VARCHAR (50) NOT NULL ,
	NAME_FIELD VARCHAR (50) NOT NULL ,
	SHOW_FIELD VARCHAR (300) ,
	RETURN_FIELD VARCHAR (300) ,
	SHEARCH_FIELD VARCHAR (300) ,
	SHOW_NAME VARCHAR (500) ,
	HELP_TABLE VARCHAR (40) NOT NULL ,
	HELP_NOTE VARCHAR (100) ,
	DATASOURCE VARCHAR (60) ,
	NOTE VARCHAR (30) ,
	NOTE2 VARCHAR (30) ,
	NOTE3 VARCHAR (30) 
);
ALTER TABLE PUB_COMHELP ADD CONSTRAINT PUB_COMHELP_PK PRIMARY KEY (HELP_ID);

