--PUB_ROLES 角色
INSERT INTO PUB_ROLES VALUES ('WORKFLOWCOMUSER', 'WORKFLOWCOMUSER', '工作流普通人员', '1', '0');

--PUB_TROLES 授权模板角色定义
INSERT INTO PUB_TROLES VALUES ('WORKFLOWCOMUSER', 'WORKFLOWCOMUSER', '工作流普通人员', '0', -1, '1');
---工作流---
------------
--流程类型选择
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0105');
--表单明细
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0205');
--流程明细
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0305');
--流程定义选择
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0309');

--任务列表
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0601');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0602');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0603');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0604');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0605');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0606');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0607');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0608');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0609');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0610');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0611');
--附件操作					   
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0701');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0702');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0703');
--流程操作					 
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0505');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0801');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0802');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0803');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0804');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0805');
--流程监控
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0901');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0902');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0903');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0904');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0905');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0906');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0907');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0908');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0909');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0910');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0911');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0912');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0913');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0914');

--表单操作
--属于公文扩展的资源也把它加进来 开始	   
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1003');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1004');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1005');
--属于公文扩展的资源也把它加进来 结束					   
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1006');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1007');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1008');
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1009');
--增加历史环节类型帮助
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0106');
--流程查询					   
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1101');
--表单查询
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1102');


---工作流---
------------
--流程类型选择
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0105');
--表单明细
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0205');
--流程明细
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0305');
--流程定义选择
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0309');

--任务列表
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0601');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0602');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0603');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0604');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0605');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0606');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0607');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0608');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0609');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0610');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0611');

--附件操作					   
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0701');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0702');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0703');
--流程操作					 
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0505');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0801');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0802');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0803');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0804');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0805');
--流程监控
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0901');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0902');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0903');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0904');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0905');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0906');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0907');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0908');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0909');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0910');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0911');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0912');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0913');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0914');
--表单操作	
--属于公文扩展的资源也把它加进来 开始
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1003');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1004');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1005');
--属于公文扩展的资源也把它加进来 结束					   
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1006');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1007');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1008');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1009');
--表单查询
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1102');

--工作流报表
--普通人员只有查询的权限
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1601') ;
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1601') ;
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1602') ;
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1602') ;
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1603') ;
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1603') ;
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1604') ;
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER' ,'WFREPORT1604') ;

--2005.11.29修正
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1501');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW1501');
--2006.04.20增加,流程定义选择
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0806');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0806');
--2006.04.20增加,附件选择
INSERT INTO PUB_ROLE_RESOURCE VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0704');
INSERT INTO PUB_TROLE_OPTS VALUES ('WORKFLOWCOMUSER', 'WORKFLOW0704');

