INSERT INTO MP_SUBSCRIBER_TYPE(SUBSCR_TYPE_CODE, SUBSCR_TYPE_NAME ) VALUES ( 'OuterUser', '外部用户' );  
INSERT INTO MP_SUBSCRIBER_TYPE(SUBSCR_TYPE_CODE, SUBSCR_TYPE_NAME ) VALUES ( 'ExtendUser', '扩展用户' );  
INSERT INTO MP_SUBSCRIBER_TYPE(SUBSCR_TYPE_CODE, SUBSCR_TYPE_NAME ) VALUES ( 'User', '系统用户' );  



 
INSERT INTO MP_MESSAGE_TYPE(MSG_TYPE_CODE, MSG_TYPE_NAME, IS_COMMON_MSG, OBJECT_TABLE_NAME, SUBSCR_LIMIT, MANNER_LIMIT ) VALUES ( '1', '公文消息', '1', '', '*', 'DB;Email' );  
INSERT INTO MP_MESSAGE_TYPE(MSG_TYPE_CODE, MSG_TYPE_NAME, IS_COMMON_MSG, OBJECT_TABLE_NAME, SUBSCR_LIMIT, MANNER_LIMIT ) VALUES ( '2', '采购消息', '1', '', '*', '*' );  
INSERT INTO MP_MESSAGE_TYPE(MSG_TYPE_CODE, MSG_TYPE_NAME, IS_COMMON_MSG, OBJECT_TABLE_NAME, SUBSCR_LIMIT, MANNER_LIMIT ) VALUES ( '3', '流程消息', '1', '', '*', '*' );  
INSERT INTO MP_MESSAGE_TYPE(MSG_TYPE_CODE, MSG_TYPE_NAME, IS_COMMON_MSG, OBJECT_TABLE_NAME, SUBSCR_LIMIT, MANNER_LIMIT ) VALUES ( '4', '系统消息', '1', '', '*', '*' );  
INSERT INTO MP_MESSAGE_TYPE(MSG_TYPE_CODE, MSG_TYPE_NAME, IS_COMMON_MSG, OBJECT_TABLE_NAME, SUBSCR_LIMIT, MANNER_LIMIT ) VALUES ( '5', '订单消息', '1', '', '*', '*' ); 

INSERT INTO MP_INCEPT_MANNER(RECEIVE_MANNER_CODE, RECEIVE_MANNER_NAME ) VALUES ( 'Mail', '邮件' );  
INSERT INTO MP_INCEPT_MANNER(RECEIVE_MANNER_CODE, RECEIVE_MANNER_NAME ) VALUES ( 'DB', '数据库' );  

INSERT INTO MP_RECEIVE_ADDRESS(RECEIVE_ADDRESS_ID, SUBSCR_TYPE_CODE, RECEIVE_MANNER_CODE, OBJECT_TABLE_NAME, SUBSCRIBERID_FIELD, SUBSCRIBERID_FIELD_TYPE, ADDRESS_FIELD ) VALUES ( '1', 'User', 'Mail', 'PUB_USERS', 'USER_ID', 'String', 'E_MAIL' );   



  
 

