CREATE TABLE SERVICE_TASK_INFO (
	ID VARCHAR(32) NOT NULL, 
	SERVICE VARCHAR(50) NOT NULL, 
	METHOD VARCHAR(50) NOT NULL, 
	REGISTER_TIME CHAR(17) , 
	START_TIME CHAR(17) , 
	END_TIME CHAR(17) , 
	STATUS INTEGER , 
	DESCRIPTION VARCHAR(100) NOT NULL, 
	CONSTRAINT SERV_TASKINFO_PK PRIMARY KEY (id)
) ;