CREATE TABLE ei.PUB_DOC_CONTENT
(
            FILE_ID VARCHAR (30) NOT NULL ,
            FILE_NAME VARCHAR (300) NOT NULL ,
            FILE_TYPE VARCHAR (50) ,
            CONTENT blob
) ;

CREATE TABLE MAINBLOB
(
    MAIN_ID VARCHAR (30) NOT NULL,
    MAIN_OPERATORCODE VARCHAR (30) NOT NULL,
    MAIN_OPERATEDATE VARCHAR (8) NOT NULL
);

CREATE TABLE BLOBITEM
(
    MAIN_ID VARCHAR (30) NOT NULL,
    FILE_ID VARCHAR (30) NOT NULL,
    FILE_NAME VARCHAR (100),
    FILE_TYPE VARCHAR (30),
    FILE_CONTENT blob
);
ALTER TABLE MAINBLOB ADD CONSTRAINT MAINBLOB_PK PRIMARY KEY (MAIN_ID);
ALTER TABLE BLOBITEM ADD CONSTRAINT BLOBITEM_PK PRIMARY KEY (MAIN_ID,FILE_ID);
ALTER TABLE BLOBITEM ADD CONSTRAINT BLOBITEM_FK1 FOREIGN KEY (MAIN_ID) REFERENCES MAINBLOB (MAIN_ID);



CREATE TABLE LS_EMPLOYEE
(
            EMPLOYEE_CODE VARCHAR (30) NOT NULL ,
            EMPLOYEE_SEX CHAR (1) NOT NULL ,
            EMPLOYEE_NAME VARCHAR (30) NOT NULL ,
            EMPLOYEE_AGE INTEGER NOT NULL ,
            EMPLOYEE_MARRY CHAR (1) NOT NULL ,
            EMPLOYEE_BIRTH CHAR (8) NOT NULL ,
            EMPLOYEE_ENTER_DATE CHAR (8) NOT NULL ,
            EMPLOYEE_COMPANY VARCHAR (30) NOT NULL ,
            EMPLOYEE_DEGREE VARCHAR (2) NOT NULL ,
            EMPLOYEE_FAX VARCHAR (15) NOT NULL ,
            EMPLOYEE_COUNTRY VARCHAR (15) NOT NULL ,
            EMPLOYEE_PROVINCE VARCHAR (15) NOT NULL ,
            EMPLOYEE_CITY VARCHAR (15) NOT NULL ,
            EMPLOYEE_PHONE CHAR (11) NOT NULL ,
            EMPLOYEE_DEPT VARCHAR (15) NOT NULL ,
            EMPLOYEE_POST CHAR (6) NOT NULL ,
            EMPLOYEE_PREFERENCE VARCHAR (8) NOT NULL ,
            EMPLOYEE_IMAGECONTENT  blob ,
            EMPLOYEE_NOTE VARCHAR (100) NOT NULL 
);
ALTER TABLE LS_EMPLOYEE ADD CONSTRAINT LS_EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_CODE);

